### ISSUE TITLE
运行h5，报了错

### ISSUE THREAD

**Issue by panwent** [wildfirechat/web-chat#5]
λ npm install
D:\Node\node_modules\npm\node_modules\npmlog\log.js:57
log.progressEnabled = log.gauge.isEnabled()
                                ^

TypeError: log.gauge.isEnabled is not a function
    at Object.<anonymous> (D:\Node\node_modules\npm\node_modules\npmlog\log.js:57:33)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at D:\Node\node_modules\npm\bin\npm-cli.js:22:13
    at Object.<anonymous> (D:\Node\node_modules\npm\bin\npm-cli.js:152:3)
D:\Node\node_modules\npm\node_modules\npmlog\log.js:57
log.progressEnabled = log.gauge.isEnabled()
                                ^

TypeError: log.gauge.isEnabled is not a function
    at Object.<anonymous> (D:\Node\node_modules\npm\node_modules\npmlog\log.js:57:33)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at D:\Node\node_modules\npm\bin\npm-cli.js:22:13
    at Object.<anonymous> (D:\Node\node_modules\npm\bin\npm-cli.js:152:3)

这个该怎么解决呢？

**Comment by imndx** [comment]
请参考：https://github.com/npm/npmlog/issues/48
